# Generated by Django 5.2.1 on 2025-06-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_academic_performance', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(),
        ),
    ]
