# Generated by Django 5.2.1 on 2025-06-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_academic_performance', '0003_alter_score_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
